import type { Metadata } from 'next'
import localFont from 'next/font/local'
import LenisProvider from './components/lenis-provider'
import StringTuneProvider from './components/string-tune-provider'
import './globals.css'

const satoshi = localFont({
  src: '../public/fonts/satoshi.ttf',
  variable: '--font-satoshi',
  weight: '300 900',
  display: 'swap',
})

const ppRightDidone = localFont({
  src: '../public/fonts/pp-right-didone-light.otf',
  variable: '--font-didone',
  weight: '300',
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      lang="en"
      className={`${satoshi.variable} ${ppRightDidone.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col font-sans">
        <LenisProvider>
          <StringTuneProvider>{children}</StringTuneProvider>
        </LenisProvider>
      </body>
    </html>
  )
}
